# Generated by Django 5.1.4 on 2025-07-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repostimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='RePost',
        ),
        migrations.DeleteModel(
            name='RePostImage',
        ),
    ]
